services:
  moderation-bot:
    container_name: "moderation-bot"
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/home/node/moderation-bot/.env
